version: "3.8"

services:
  fe-incube:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fe-incube
    restart: unless-stopped
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_BACKEND_API_URL=http://10.0.3.37:8000
      - NEXTAUTH_URL=http://localhost:80
    command: "npm run start"

  nginx:
    image: nginx:stable-alpine
    container_name: fe-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - fe-incube
