version: "3.8"

services:
  fe-incube:
    image: fuadgrimaldi/fe-incube:latest
    container_name: fe-incube
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env.production

  fe-nginx:
    image: nginx:stable-alpine
    container_name: fe-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - fe-incube
